---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Ensure /var/local/libexec/edpm-start-podman-container exists
  ansible.builtin.import_role:
    name: edpm_container_manage
    tasks_from: shutdown.yml

- name: Update multipathd health check script
  ansible.builtin.include_tasks:
    file: healthchecks.yml

- name: Stop and disable old standalone container
  ansible.builtin.systemd_service:
    name: edpm_multipathd
    state: stopped
    enabled: false
  become: true

- name: Cleanup old standalone container
  ansible.builtin.file:
    path: /etc/systemd/system/edpm_multipathd.service
    state: absent
  become: true

- name: Render multipathd quadlet file
  ansible.builtin.template:
    src: templates/multipathd.yaml.j2
    dest: /etc/containers/systemd/multipathd.yaml
  become: true
  register: manage_multipathd_stat

- name: Start multipathd quadlet
  ansible.builtin.systemd_service:
    name: edpm-compute@multipathd
    state: restarted
  become: true

- name: Check if the multipathd container restart is required
  ansible.builtin.stat:
    path: "{{ edpm_multipathd_restart_sentinel }}"
  register: multipath_restart_stat

# Existence the edpm_multipathd_restart_sentinel file on the host
# indicates that restart of the multipathd container is needed to refresh
# /etc/multipathd.conf
# sentinel file will exist on an initial deployment, but the restart is
# actually needed only if the service is already running, so we check if
# the manage_multipathd_stat changed.

- name: Restart containers when the multipath configuration changes
  when:
    - not manage_multipathd_stat.changed|bool
    - multipath_restart_stat.stat.exists|bool
  become: true
  block:
    - name: Identify containers using /etc/multipath.conf
      ansible.builtin.command: "{{ edpm_container_cli }} ps --filter volume=/etc/multipath.conf --format {{ '{{' }}.Names{{ '}}' }}"
      register: multipath_conf_containers
      changed_when: false

    - name: "Restart container to refresh its /etc/multipath.conf"
      ansible.builtin.systemd:
        name: "edpm_compute@{{ multipath_container }}"
        state: restarted
      loop: "{{ multipath_conf_containers.stdout_lines | default([]) }}"
      loop_control:
        loop_var: multipath_container

- name: Remove multipathd container restart sentinel file
  become: true
  ansible.builtin.file:
    path: "{{ edpm_multipathd_restart_sentinel }}"
    state: absent
