---
# Copyright 2019 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


edpm_kernel_modules:
  br_netfilter: {}
  nf_conntrack: {}

edpm_kernel_sysctl_settings:
  fs.inotify.max_user_instances:
    value: 1024
  fs.suid_dumpable:
    value: 0
  kernel.dmesg_restrict:
    value: 1
  kernel.pid_max:
    value: 1048576
  net.bridge.bridge-nf-call-arptables:
    value: 1
  net.bridge.bridge-nf-call-ip6tables:
    value: 1
  net.bridge.bridge-nf-call-iptables:
    value: 1
  net.core.netdev_max_backlog:
    value: 10000
  net.ipv4.conf.all.arp_accept:
    value: 1
  net.ipv4.conf.all.arp_notify:
    value: 1
  net.ipv4.conf.all.log_martians:
    value: 1
  net.ipv4.conf.all.rp_filter:
    value: 1
  net.ipv4.conf.all.secure_redirects:
    value: 0
  net.ipv4.conf.all.send_redirects:
    value: 0
  net.ipv4.conf.default.accept_redirects:
    value: 0
  net.ipv4.conf.default.log_martians:
    value: 1
  net.ipv4.conf.default.secure_redirects:
    value: 0
  net.ipv4.conf.default.send_redirects:
    value: 0
  net.ipv4.ip_forward:
    value: 1
  net.ipv4.ip_local_reserved_ports:
    value: "35357,49000-49001"
  net.ipv4.ip_nonlocal_bind:
    value: 1
  net.ipv4.neigh.default.gc_thresh1:
    value: 1024
  net.ipv4.neigh.default.gc_thresh2:
    value: 2048
  net.ipv4.neigh.default.gc_thresh3:
    value: 4096
  net.ipv4.tcp_keepalive_intvl:
    value: 1
  net.ipv4.tcp_keepalive_probes:
    value: 5
  net.ipv4.tcp_keepalive_time:
    value: 5
  net.ipv6.conf.all.accept_ra:
    value: 0
  net.ipv6.conf.all.accept_redirects:
    value: 0
  net.ipv6.conf.all.autoconf:
    value: 0
  net.ipv6.conf.all.disable_ipv6:
    value: 0
  net.ipv6.conf.all.forwarding:
    value: 0
  net.ipv6.conf.all.ndisc_notify:
    value: 1
  net.ipv6.conf.default.accept_ra:
    value: 0
  net.ipv6.conf.default.accept_redirects:
    value: 0
  net.ipv6.conf.default.autoconf:
    value: 0
  net.ipv6.conf.default.disable_ipv6:
    value: 0
  net.ipv6.conf.lo.disable_ipv6:
    value: 0
  net.ipv6.ip_nonlocal_bind:
    value: 1
  net.netfilter.nf_conntrack_max:
    value: 500000
  net.nf_conntrack_max:
    value: 500000
  vm.unprivileged_userfaultfd:
    value: 1
