---
# defaults file for edpm_ovn

# service name this role manages
edpm_neutron_metadata_service_name: neutron-metadata

# seconds between retries for download tasks
edpm_neutron_metadata_images_download_delay: 5

# number of retries for download tasks
edpm_neutron_metadata_images_download_retries: 5

edpm_neutron_metadata_config_src: "/var/lib/openstack/configs/{{ edpm_neutron_metadata_service_name }}"
edpm_neutron_metadata_agent_config_dir: /var/lib/config-data/ansible-generated/neutron-ovn-metadata-agent
edpm_neutron_metadata_agent_lib_dir: "/var/lib/neutron"

edpm_neutron_metadata_agent_image: "quay.io/podified-antelope-centos9/openstack-neutron-metadata-agent-ovn:current-podified"

edpm_neutron_metadata_common_volumes:
  - path: /run/openvswitch
    mountPath: /run/openvswitch
    name: run-openvswitch
    readOnly: false
  - path: "{{ edpm_neutron_metadata_agent_config_dir }}"
    mountPath: /etc/neutron.conf.d
    name: etc-neutron-conf-d
    readOnly: false
  - path: /run/netns
    mountPath: /run/netns
    name: run-netns
    readOnly: false
  - path: /var/lib/kolla/config_files/ovn_metadata_agent.json
    mountPath: /var/lib/kolla/config_files/config.json
    name: kolla-config
    readOnly: true
  - path: "{{ edpm_neutron_metadata_agent_lib_dir }}"
    mountPath: /var/lib/neutron
    name: var-lib-shared
    readOnly: false
  - path: "{{ edpm_neutron_metadata_agent_lib_dir }}/ovn_metadata_haproxy_wrapper"
    mountPath: /usr/local/bin/haproxy
    name: haproxy
    readOnly: true
  - path: "{{ edpm_neutron_metadata_agent_lib_dir }}/kill_scripts"
    mountPath: /etc/neutron/kill_scripts
    name: kill-scripts
    readOnly: true

# Sidecar containers settings
edpm_neutron_metadata_agent_sidecar_debug: false
edpm_neutron_metadata_agent_sidecar_haproxy_image_name: "{{ edpm_neutron_metadata_agent_image }}"

# Neutron conf
# edpm_ovn_metadata_agent_DEFAULT_: ''
# oslo_concurrency
edpm_neutron_metadata_agent_oslo_concurrency_lock_patch: '$state_path/lock'
# agent
edpm_neutron_metadata_agent_agent_report_interval: '300'

# rootwrap.conf
edpm_neutron_metadata_agent_rootwrap_DEFAULT_filters_path: '/usr/share/neutron/rootwrap'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_exec_dirs: '/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin,/etc/neutron/kill_scripts'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_use_syslog: 'False'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_syslog_log_facility: 'syslog'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_syslog_log_level: 'ERROR'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_daemon_timeout: '600'
edpm_neutron_metadata_agent_rootwrap_DEFAULT_rlimit_nofile: '1024'

# neutron-ovn-metadata-agent.conf
edpm_neutron_metadata_agent_DEFAULT_debug: 'True'
edpm_neutron_metadata_agent_DEFAULT_metadata_workers: '1'
edpm_neutron_metadata_agent_DEFAULT_state_path: '/var/lib/neutron'
edpm_neutron_metadata_agent_agent_root_helper: 'sudo neutron-rootwrap /etc/neutron/rootwrap.conf'
edpm_neutron_metadata_agent_ovs_ovsdb_connection: 'tcp:127.0.0.1:6640'
edpm_neutron_metadata_agent_ovs_ovsdb_connection_timeout: '180'
edpm_neutron_metadata_agent_ovn_ovsdb_probe_interval: '60000'

# tls
edpm_neutron_metadata_agent_tls_enabled: "{{ edpm_tls_certs_enabled | default(False) }}"

edpm_neutron_metadata_tls_cacert_bundle_src: "/var/lib/openstack/cacerts/{{ edpm_neutron_metadata_service_name }}/tls-ca-bundle.pem"
edpm_neutron_metadata_tls_cacert_bundle_dest: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
edpm_neutron_metadata_tls_cacert_volumes: []

edpm_neutron_metadata_tls_volumes:
  - path: "/var/lib/openstack/certs/{{ edpm_neutron_metadata_service_name }}/default/ca.crt"
    mountPath: /etc/pki/tls/certs/ovndbca.crt
    name: ovndb-ca-crt
    readOnly: true
  - path: "/var/lib/openstack/certs/{{ edpm_neutron_metadata_service_name }}/default/tls.crt"
    mountPath: /etc/pki/tls/certs/ovndb.crt
    name: ovndb-crt
    readOnly: true
  - path: "/var/lib/openstack/certs/{{ edpm_neutron_metadata_service_name }}/default/tls.key"
    mountPath: /etc/pki/tls/private/ovndb.key
    name: ovndb-key
    readOnly: true

edpm_neutron_metadata_healthcheck: true
