---
driver:
  name: podman
platforms:
  - name: instance
    image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
    registry:
      url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
    command: /sbin/init
    dockerfile: ../../../../molecule/common/Containerfile.j2
    privileged: true
    ulimits: &ulimit
      - host
provisioner:
  inventory:
    hosts:
      all:
        hosts:
          instance:
            ansible_python_interpreter: /usr/bin/python3
  name: ansible
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - check
    - verify
    - destroy

verifier:
  name: testinfra
  env:
    EDPM_NVDIMM_PMEM_NAMESPACES: "12G:ns12g,12G:ns12g"
