---
- name: Find desired default hugepage size
  when: hp.value.default | default(false) | bool
  ansible.builtin.set_fact:
    _edpm_default_hugepages: "{{ hp.key }}"
  loop: "{{ _edpm_kernel_hugepages | dict2items }}"
  loop_control:
    loop_var: hp

- name: Storing non-configured hugepages
  ansible.builtin.set_fact:
    _nonconfig_hugepages: >-
      {% if (hp.key | int not in _edpm_kernel_hugepages) -%}
      {{ _nonconfig_hugepages |
         combine({
           hp.key | int: _converted_hugepages[hp.key |  int]
         })
       -}}
      {% else -%}
      {{ _nonconfig_hugepages |combine({}) -}}
      {% endif -%}
  loop: "{{ _converted_hugepages | dict2items }}"
  loop_control:
    loop_var: hp

- name: Validating against hugepages config received from EDPM
  ansible.builtin.set_fact:
    _validated_hugepages: >-
      {% set validated = false -%}
      {% set _tmp_dict = {} -%}
      {% for hp in _edpm_kernel_hugepages | dict2items -%}
      {%   if (
             hp.key | int in _converted_hugepages and
             _converted_hugepages[hp.key | int] | int == hp.value.count | int and
             (_configured_default_size | int == hp.key | int) == hp.value.default | default(false)
           ) -%}
      {%     set validated = true -%}
      {%   endif -%}
      {%   set _ = _tmp_dict.update({ hp.key | int: validated }) -%}
      {% endfor -%}
      {% if edpm_kernel_hugepages_remove | bool -%}
      {%   for hp in _nonconfig_hugepages | dict2items -%}
      {%     set _ = _tmp_dict.update({ hp.key | int: false }) -%}
      {%   endfor -%}
      {% endif -%}
      {{ _tmp_dict }}

- name: Determining the default hugepagesz
  ansible.builtin.set_fact:
    _desired_default_hugepages: "{{ _edpm_default_hugepages | default(_configured_default_size | default(0)) | int }}"

- name: Determining if any hugepage configuration needs to be re-written
  ansible.builtin.set_fact:
    _hugepages_modification: >-
      {{ (not _validated_hugepages.values() is all) | bool -}}

- name: Making sure that we have a default hugepagesz
  when: _desired_default_hugepages | int == 0
  ansible.builtin.fail:
    msg: |
      Unable to determine a default hugepagesize.
      Please enable the default flag on at least one pagesize parameter.
