---
- name: Molecule tests
  hosts: localhost
  connection: local
  vars:
    role_dir: "{{ [
      lookup('ansible.builtin.env', 'GITHUB_WORKSPACE'), 'roles', lookup('ansible.builtin.env', 'ROLE_NAME')] | path_join }}"
  tasks:
  - debug:
      msg: "{{ role_dir }}"
  - name: Run molecule tests
    ansible.builtin.shell:
      chdir: "{{ role_dir }}"
      cmd: molecule test --all
