---

# Note: Previous versions of EDPM used log file with podman exec specific data
#       to provide health check execution results to sensubility. This serves for
#       cleanup of unneeded rsyslog configuration since sensubility is fetching
#       data straight from podman socket

- name: Remove unneeded podman-related rsyslog configuration
  ansible.builtin.file:
    path: /etc/rsyslog.d/openstack-healthcheck.conf
    state: absent
  ignore_errors: true
  notify: Restart rsyslog
