---
- name: Check if discover hosts is required
  when:
    - not edpm_nova_compute_additional_cell|bool
    - nova_cellv2_discovery_done is not defined
  block:
    - name: Discover via nova_manager?
      ansible.builtin.set_fact:
        nova_cellv2_discovery_delegate_host: "{{ groups['nova_manager'][0] }}"
        nova_cellv2_discovery_container: nova_manager
      when:
        - groups['nova_manager'] is defined and (groups['nova_manager']|length>0)
    - name: Discover via nova_api?
      ansible.builtin.set_fact:
        nova_cellv2_discovery_delegate_host: "{{ groups['nova_api'][0] }}"
        nova_cellv2_discovery_container: nova_api
      when:
        - nova_cellv2_discovery_delegate_host is not defined
        - groups['nova_api'] is defined and (groups['nova_api']|length>0)
    - name: Warn if no discovery host available
      ansible.builtin.fail:
        msg: 'No hosts available to run nova cell_v2 host discovery.'
      ignore_errors: true
      when:
        - nova_cellv2_discovery_delegate_host is not defined
    - name: Discovering nova hosts
      ansible.builtin.command: /bin/podman exec {{ nova_cellv2_discovery_container }} nova-manage cell_v2 discover_hosts --by-service
      become: true
      changed_when: false
      delegate_to: '{{ nova_cellv2_discovery_delegate_host }}'
      when:
        - nova_cellv2_discovery_delegate_host is defined
    # Could be included multiple times so ensure it only runs once
    - name: Get nova_cellv2_discovery_done fact
      ansible.builtin.set_fact:
        nova_cellv2_discovery_done: true
