---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Ensure /var/lib/container-config-scripts exists
  ansible.builtin.file:
    path: /var/lib/container-config-scripts
    state: directory
    mode: 0755

- name: Copy nova_statedir_ownership.py to /var/lib/container-config-scripts
  ansible.builtin.copy:
    src: files/nova_statedir_ownership.py
    dest: /var/lib/container-config-scripts/nova_statedir_ownership.py
    mode: 0644

- name: Manage nova_compute_statedir_owner container
  ansible.builtin.include_role:
    name: edpm_container_standalone
  vars:
    edpm_container_standalone_service: nova_compute_statedir_owner
    edpm_container_standalone_container_defs:
      nova_compute_statedir_owner: "{{ lookup('template', 'nova_compute_statedir_owner.yaml.j2') | from_yaml }}"

- name: Manage nova_compute_init_log container
  ansible.builtin.include_role:
    name: edpm_container_standalone
  vars:
    edpm_container_standalone_service: nova_compute_init_log
    edpm_container_standalone_container_defs:
      nova_compute_init_log: "{{ lookup('template', 'nova_compute_init_log.yaml.j2') | from_yaml }}"

- name: Manage nova_wait_for_compute_service container
  when: edpm_nova_compute_additional_cell|bool
  ansible.builtin.include_role:
    name: edpm_container_standalone
  vars:
    edpm_container_standalone_service: nova_wait_for_compute_service
    edpm_container_standalone_container_defs:
      nova_wait_for_compute_service: "{{ lookup('template', 'nova_wait_for_compute_service.yaml.j2') | from_yaml }}"
    edpm_container_standalone_kolla_config_files:
      nova_wait_for_compute_service: "{{ lookup('file', 'files/nova_wait_for_compute_service.yaml') | from_yaml }}"

- name: Manage nova_compute container
  ansible.builtin.include_role:
    name: edpm_container_standalone
  vars:
    edpm_container_standalone_service: nova_compute
    edpm_container_standalone_container_defs:
      nova_compute: "{{ lookup('template', 'nova_compute.yaml.j2') | from_yaml }}"
    edpm_container_standalone_kolla_config_files:
      nova_compute: "{{ lookup('template', 'templates/kolla_config/nova_compute.yaml.j2') | from_yaml }}"
