---
# Copyright 2020 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "edpm_container_standalone"

# Service name. Use for creating directories, container labels, etc
edpm_container_standalone_service: ""
# Directory for kolla config files
edpm_container_standalone_kolla_config_dir: /var/lib/kolla/config_files
# Directory for container startup configs
edpm_container_standalone_container_startup_config_dir: /var/lib/edpm-config/container-startup-config
# Hash with keys of container name and value of YAML kolla config file.
edpm_container_standalone_kolla_config_files: {}
# Hash with keys of container name and value of YAML container definition
edpm_container_standalone_container_defs: {}

# List of common volumes that can be included in the template of a container
# definition to include the most common volumes.
edpm_container_standalone_common_volumes:
  - path: /etc/hosts
    mountPath: /etc/hosts
    readOnly: true
    name: etc-hosts
  - path: /etc/localtime
    mountPath: /etc/localtime
    readOnly: true
    name: etc-localtime
  # OpenSSL trusted CAs
  - path: /etc/pki/ca-trust/extracted
    mountPath: /etc/pki/ca-trust/extracted
    readOnly: true
    name: ca-extracted
  - path: /etc/pki/ca-trust/source/anchors
    mountPath: /etc/pki/ca-trust/source/anchors
    readOnly: true
    name: anchors
  - path: /etc/pki/tls/certs/ca-bundle.crt
    mountPath: /etc/pki/tls/certs/ca-bundle.crt
    readOnly: true
    name: ca-bundle
  - path: /etc/pki/tls/certs/ca-bundle.trust.crt
    mountPath: /etc/pki/tls/certs/ca-bundle.trust.crt
    readOnly: true
    name: ca-trust-bundle
  - path: /etc/pki/tls/cert.pem
    mountPath: /etc/pki/tls/cert.pem
    readOnly: true
    name: tls-cert
  # Syslog socket
  - path: /dev/log
    mountPath: /dev/log
    readOnly: false
    name: dev-log

# List of volumes included when internal tls is enabled
edpm_container_standalone_internal_tls_volumes:
  - path: /etc/pki/tls/certs/httpd
    mountPath: /etc/pki/tls/certs/httpd
    readOnly: true
    name: certs-httpd
  - path: /etc/pki/tls/private/httpd
    mountPath: /etc/pki/tls/private/httpd
    readOnly: true
    name: private-httpd

# Internal TLS vars. These vars are not prefixed with the role name as they are
# intended to be set from other services/roles.
edpm_enable_internal_tls: false
edpm_internal_tls_ca_file: /etc/ipa/ca.crt

edpm_container_standalone_volumes: "{{
    edpm_enable_internal_tls |
      ternary(
        edpm_container_standalone_common_volumes +
          edpm_container_standalone_internal_tls_volumes +
          [edpm_internal_tls_ca_file ~ ':' ~ edpm_internal_tls_ca_file ~ ':ro'],
        edpm_container_standalone_common_volumes)
  }}"

edpm_deploy_identifier: ''
edpm_iscsid_config_volume: /var/lib/config-data/ansible-generated/iscsid
